# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: sb_stats.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import sb_stats_pb2


class StatsServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetStats(self, stream: 'grpclib.server.Stream[sb_stats_pb2.GetStatsRequest, sb_stats_pb2.GetStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def QueryStats(self, stream: 'grpclib.server.Stream[sb_stats_pb2.QueryStatsRequest, sb_stats_pb2.QueryStatsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetSysStats(self, stream: 'grpclib.server.Stream[sb_stats_pb2.SysStatsRequest, sb_stats_pb2.SysStatsResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/v2ray.core.app.stats.command.StatsService/GetStats': grpclib.const.Handler(
                self.GetStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                sb_stats_pb2.GetStatsRequest,
                sb_stats_pb2.GetStatsResponse,
            ),
            '/v2ray.core.app.stats.command.StatsService/QueryStats': grpclib.const.Handler(
                self.QueryStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                sb_stats_pb2.QueryStatsRequest,
                sb_stats_pb2.QueryStatsResponse,
            ),
            '/v2ray.core.app.stats.command.StatsService/GetSysStats': grpclib.const.Handler(
                self.GetSysStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                sb_stats_pb2.SysStatsRequest,
                sb_stats_pb2.SysStatsResponse,
            ),
        }


class StatsServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/v2ray.core.app.stats.command.StatsService/GetStats',
            sb_stats_pb2.GetStatsRequest,
            sb_stats_pb2.GetStatsResponse,
        )
        self.QueryStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/v2ray.core.app.stats.command.StatsService/QueryStats',
            sb_stats_pb2.QueryStatsRequest,
            sb_stats_pb2.QueryStatsResponse,
        )
        self.GetSysStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/v2ray.core.app.stats.command.StatsService/GetSysStats',
            sb_stats_pb2.SysStatsRequest,
            sb_stats_pb2.SysStatsResponse,
        )
