# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: wildosnode.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

from . import wildosnode_pb2


class WildosServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SyncUsers(self, stream: 'grpclib.server.Stream[wildosnode_pb2.UserData, wildosnode_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def RepopulateUsers(self, stream: 'grpclib.server.Stream[wildosnode_pb2.UsersData, wildosnode_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def FetchBackends(self, stream: 'grpclib.server.Stream[wildosnode_pb2.Empty, wildosnode_pb2.BackendsResponse]') -> None:
        pass

    @abc.abstractmethod
    async def FetchUsersStats(self, stream: 'grpclib.server.Stream[wildosnode_pb2.Empty, wildosnode_pb2.UsersStats]') -> None:
        pass

    @abc.abstractmethod
    async def FetchBackendConfig(self, stream: 'grpclib.server.Stream[wildosnode_pb2.Backend, wildosnode_pb2.BackendConfig]') -> None:
        pass

    @abc.abstractmethod
    async def RestartBackend(self, stream: 'grpclib.server.Stream[wildosnode_pb2.RestartBackendRequest, wildosnode_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def StreamBackendLogs(self, stream: 'grpclib.server.Stream[wildosnode_pb2.BackendLogsRequest, wildosnode_pb2.LogLine]') -> None:
        pass

    @abc.abstractmethod
    async def GetBackendStats(self, stream: 'grpclib.server.Stream[wildosnode_pb2.Backend, wildosnode_pb2.BackendStats]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/wildosnode.WildosService/SyncUsers': grpclib.const.Handler(
                self.SyncUsers,
                grpclib.const.Cardinality.STREAM_UNARY,
                wildosnode_pb2.UserData,
                wildosnode_pb2.Empty,
            ),
            '/wildosnode.WildosService/RepopulateUsers': grpclib.const.Handler(
                self.RepopulateUsers,
                grpclib.const.Cardinality.UNARY_UNARY,
                wildosnode_pb2.UsersData,
                wildosnode_pb2.Empty,
            ),
            '/wildosnode.WildosService/FetchBackends': grpclib.const.Handler(
                self.FetchBackends,
                grpclib.const.Cardinality.UNARY_UNARY,
                wildosnode_pb2.Empty,
                wildosnode_pb2.BackendsResponse,
            ),
            '/wildosnode.WildosService/FetchUsersStats': grpclib.const.Handler(
                self.FetchUsersStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                wildosnode_pb2.Empty,
                wildosnode_pb2.UsersStats,
            ),
            '/wildosnode.WildosService/FetchBackendConfig': grpclib.const.Handler(
                self.FetchBackendConfig,
                grpclib.const.Cardinality.UNARY_UNARY,
                wildosnode_pb2.Backend,
                wildosnode_pb2.BackendConfig,
            ),
            '/wildosnode.WildosService/RestartBackend': grpclib.const.Handler(
                self.RestartBackend,
                grpclib.const.Cardinality.UNARY_UNARY,
                wildosnode_pb2.RestartBackendRequest,
                wildosnode_pb2.Empty,
            ),
            '/wildosnode.WildosService/StreamBackendLogs': grpclib.const.Handler(
                self.StreamBackendLogs,
                grpclib.const.Cardinality.UNARY_STREAM,
                wildosnode_pb2.BackendLogsRequest,
                wildosnode_pb2.LogLine,
            ),
            '/wildosnode.WildosService/GetBackendStats': grpclib.const.Handler(
                self.GetBackendStats,
                grpclib.const.Cardinality.UNARY_UNARY,
                wildosnode_pb2.Backend,
                wildosnode_pb2.BackendStats,
            ),
        }


class WildosServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SyncUsers = grpclib.client.StreamUnaryMethod(
            channel,
            '/wildosnode.WildosService/SyncUsers',
            wildosnode_pb2.UserData,
            wildosnode_pb2.Empty,
        )
        self.RepopulateUsers = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/RepopulateUsers',
            wildosnode_pb2.UsersData,
            wildosnode_pb2.Empty,
        )
        self.FetchBackends = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/FetchBackends',
            wildosnode_pb2.Empty,
            wildosnode_pb2.BackendsResponse,
        )
        self.FetchUsersStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/FetchUsersStats',
            wildosnode_pb2.Empty,
            wildosnode_pb2.UsersStats,
        )
        self.FetchBackendConfig = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/FetchBackendConfig',
            wildosnode_pb2.Backend,
            wildosnode_pb2.BackendConfig,
        )
        self.RestartBackend = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/RestartBackend',
            wildosnode_pb2.RestartBackendRequest,
            wildosnode_pb2.Empty,
        )
        self.StreamBackendLogs = grpclib.client.UnaryStreamMethod(
            channel,
            '/wildosnode.WildosService/StreamBackendLogs',
            wildosnode_pb2.BackendLogsRequest,
            wildosnode_pb2.LogLine,
        )
        self.GetBackendStats = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wildosnode.WildosService/GetBackendStats',
            wildosnode_pb2.Backend,
            wildosnode_pb2.BackendStats,
        )
